name: Web

on: workflow_dispatch

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Checkout HoloStats code
        uses: actions/checkout@v2
        with:
          repository: "PoiScript/HoloStats"
          path: "HoloStats"

      - name: Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        working-directory: HoloStats/web
        run: yarn install --prefer-offline

      - name: Build web
        working-directory: HoloStats/web
        run: |
          sed -i "s/GIT_COMMIT_HASH/$(git rev-parse --short HEAD)/" src/environments/*
          yarn build --prod

      - name: Build workers
        working-directory: HoloStats/web
        run: yarn tsc -P workers/tsconfig.json

      - name: Publish
        run: |
          cp -r HoloStats/web/dist/ web
          cp -r HoloStats/web/workers/dist/ workers
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add web workers
          git commit -m "Compiled at $(date)"
          git push
